#!/bin/bash

set -Eeo pipefail

AWS_DEFAULT_REGION=eu-west-2
IMAGE_REPO_NAME=deductions/pds-adaptor

function tf_plan {
  operation=$1
  cd terraform
  
  COMMIT_HASH=$(git rev-parse HEAD | cut -c 1-7)
  IMAGE_TAG=${COMMIT_HASH}

  terraform init
  terraform get # modules
  if [[ "${operation}" == "create" ]]; then
    terraform plan -var task_image_tag=$IMAGE_TAG -var-file=terraform.tfvars -out="nhs_deployment.tfplan"
  elif [[ "${operation}" == "destroy" ]]; then
    terraform plan -var task_image_tag=$IMAGE_TAG -var-file=terraform.tfvars -out="nhs_deployment.tfplan" -destroy
  else
    echo "Unknown operation (should be create or destroy), got: ${operation}"
    exit 1
  fi
}

function tf_apply {
  terraform init
  terraform get # modules
  terraform apply nhs_deployment.tfplan
  terraform output -json > tf-out.json
}

function docker_login {
  echo Logging in to Amazon ECR...
  eval $(dojo -c Dojofile-infra "aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION")
}

command="$1"
case "${command}" in
  _dep)
      echo "Running NPM Audit ..."
      npm audit
      ;;
  dep)
      dojo "./tasks _dep"
      ;;
  _build)
      npm install
      npm run build
      ;;
  build)
      dojo "./tasks _build"
      ;;
  _test)
      npm install
      npm run test
      ;;
  test)
      dojo "./tasks _test"
      ;;
  build_docker_local)
      REPOSITORY_URI=$IMAGE_REPO_NAME
      COMMIT_HASH=$(git rev-parse HEAD | cut -c 1-7)
      IMAGE_TAG=${COMMIT_HASH}
      echo Build started on `date`
      echo Building the Docker image...
      docker build -t $REPOSITORY_URI:latest .
      docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      echo Build completed on `date`
      ;;
  build_docker)
      docker_login
      AWS_ACCOUNT_ID=$(dojo -c Dojofile-infra "aws sts get-caller-identity | jq -r .Account")
      REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/$IMAGE_REPO_NAME
      ./tasks build_docker_local
      COMMIT_HASH=$(git rev-parse HEAD | cut -c 1-7)
      IMAGE_TAG=${COMMIT_HASH}
      docker tag $IMAGE_REPO_NAME $REPOSITORY_URI:$IMAGE_TAG
      docker tag $IMAGE_REPO_NAME $REPOSITORY_URI:latest
      echo "Pushing the Docker image...
      $REPOSITORY_URI:latest
      $REPOSITORY_URI:$IMAGE_TAG"
      docker push $REPOSITORY_URI:latest
      docker push $REPOSITORY_URI:$IMAGE_TAG
      ;;
  tf)
      dojo -c Dojofile-infra "bash"
      ;;
  _tf_plan)
      tf_plan "$2"
      ;;
  tf_plan)
      dojo -c Dojofile-infra "./tasks _tf_plan $2"
      ;;
  _tf_apply)
      tf_apply
      ;;
  tf_apply)
      dojo -c Dojofile-infra "./tasks _tf_apply"
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
