format_version: 4
pipelines:
  "prm-deductions-pds-adaptor":
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - build:
          clean_workspace: true
          jobs:
            dependency_check:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks dep
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test
            npm_install:
              resources:
                - docker
              artifacts:
                - build:
                    source: build
                - build:
                    source: node_modules
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build
      - docker:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: build
                    job: npm_install
                    source: build
                - fetch:
                    stage: build
                    job: npm_install
                    source: node_modules
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_docker
      - deploy_dev:
          clean_workspace: true
          jobs:
            deploy:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks tf_plan create
                # - exec:
                #     command: /bin/bash
                #     arguments:
                #       - -c
                #       - ./tasks tf_apply
